package com.demo.dao.model;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.age
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.address
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.mobile
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.height
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    private Float height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.weight
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    private Float weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.marital_status
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    private Boolean maritalStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.age
     *
     * @return the value of person.age
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.age
     *
     * @param age the value for person.age
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.address
     *
     * @return the value of person.address
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.address
     *
     * @param address the value for person.address
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.mobile
     *
     * @return the value of person.mobile
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.mobile
     *
     * @param mobile the value for person.mobile
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.height
     *
     * @return the value of person.height
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public Float getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.height
     *
     * @param height the value for person.height
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public void setHeight(Float height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.weight
     *
     * @return the value of person.weight
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.weight
     *
     * @param weight the value for person.weight
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.marital_status
     *
     * @return the value of person.marital_status
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public Boolean getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.marital_status
     *
     * @param maritalStatus the value for person.marital_status
     *
     * @mbg.generated Wed Jun 16 20:34:10 CST 2021
     */
    public void setMaritalStatus(Boolean maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
}