spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: MyHikariCP
    password: Pzh@1234#
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.14.129:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root